command: ["gunicorn", "app:app", "--bind", "0.0.0.0:8000", "--workers", "4", "--threads", "25", "--worker-class", "gthread", "--timeout", "600"]
env:
  - name: GENIE_SPACE_ID
    value: "<YOUR_GENIE_SPACE_ID>"
  - name: FLASK_PORT
    value: "8000"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "<YOUR_WAREHOUSE_ID>"
  - name: CONVERSATION_TABLE
    value: "<YOUR_CATALOG.SCHEMA.TABLE>"
